# Generated by Django 4.0.6 on 2022-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cam_no', models.IntegerField(default=None)),
                ('detection_type', models.CharField(max_length=255)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
