# Generated by Django 4.0.6 on 2022-07-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
