# Generated by Django 4.0.6 on 2022-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_system', '0002_admin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
